'use client';
import styles from './individual-screening.module.css';
type Movie={entity_id:string;name:string;release_year:number};
export type FilmPreferences={schema_version:1;favorite_entity_ids:string[];excluded_entity_ids:string[]};
export type PreferencePair={A:FilmPreferences;B:FilmPreferences};
export const emptyPreferences=():FilmPreferences=>({schema_version:1,favorite_entity_ids:[],excluded_entity_ids:[]});
export function CinemaPreferencesEditor({catalog,artists,preferences,disabled,onChange,discoveries=false}:{catalog:Movie[];artists:{A:string;B:string};preferences:PreferencePair;disabled:boolean;onChange:(value:PreferencePair)=>void;discoveries?:boolean}){
 function choose(profile:'A'|'B',id:string,value:string){const old=preferences[profile];const next={...old,favorite_entity_ids:old.favorite_entity_ids.filter(v=>v!==id),excluded_entity_ids:old.excluded_entity_ids.filter(v=>v!==id)};if(value==='favorite')next.favorite_entity_ids.push(id);if(value==='exclude')next.excluded_entity_ids.push(id);onChange({...preferences,[profile]:next})}
 return <div className={styles.preferences}><div className={styles.sectionHeading}><h2>YOUR FILM TASTES</h2><span>Explicit choices · separate for each profile</span></div><p>{discoveries?'Mark up to five films you already like to guide Qloo and the model. Known favorites will not be recommended again. Avoid unwanted films and leave at least five new candidates for each profile.':'Choose up to five favorites and fifteen movies to avoid from this catalog. Favorites guide the model; they do not guarantee satisfaction.'} Excluded movies never enter the final five. No demographic or cultural identity is inferred.</p><div className={styles.preferenceProfiles}>{(['A','B'] as const).map(profile=>{const value=preferences[profile];const eligible=catalog.filter(movie=>!value.favorite_entity_ids.includes(movie.entity_id)&&!value.excluded_entity_ids.includes(movie.entity_id)).length;return <details className={styles.preferenceProfile} key={profile}><summary>PROFILE {profile} · {artists[profile]||'Choose an artist'}<small>{value.favorite_entity_ids.length}/5 favorites · {value.excluded_entity_ids.length}/15 exclusions{discoveries?` · ${eligible} new candidates`:''}</small></summary>{discoveries&&eligible<5&&<p role="alert">Leave at least five new candidates before preparing this plan.</p>}<div className={styles.filmChoices}>{catalog.map(movie=>{const chosen=value.favorite_entity_ids.includes(movie.entity_id)?'favorite':value.excluded_entity_ids.includes(movie.entity_id)?'exclude':'';const minimumReached=discoveries&&eligible<=5&&chosen==='';return <label key={movie.entity_id}><span>{movie.name}<small>{movie.release_year}</small></span><select aria-label={`Profile ${profile}: ${movie.name}`} value={chosen} disabled={disabled} onChange={e=>choose(profile,movie.entity_id,e.target.value)}><option value="">NO PREFERENCE</option><option value="favorite" disabled={minimumReached||value.favorite_entity_ids.length>=5&&chosen!=='favorite'}>{discoveries?'KNOWN FAVORITE':'FAVORITE'}</option><option value="exclude" disabled={minimumReached||value.excluded_entity_ids.length>=15&&chosen!=='exclude'}>AVOID</option></select></label>})}</div></details>})}</div></div>;
}
export type CinemaRow={preferences_sha256:string;intent_sha256:string;raw_ranking:string[];delivered:string[];baseline_delivered:string[];raw_ranking_sha256:string;delivery_sha256:string;eligible_count:number;selection_changed:boolean;excluded_removed:string[];preference_gate:string;known_favorite_count?:number;discovery_count?:number};
export function CinemaResults({results,catalog,gate,discoveries=false}:{results:Record<string,CinemaRow>;catalog:Movie[];gate:string;discoveries?:boolean}){
 const names=new Map(catalog.map(movie=>[movie.entity_id,movie.name]));
 return <section className={styles.cinemaResults} aria-labelledby="cinema-result-title"><div className={styles.sectionHeading}><h2 id="cinema-result-title">{discoveries?'NEW FILM DISCOVERIES':'FILM PREFERENCE REVIEW'}</h2><strong data-state={gate}>{gate}</strong></div><p>These checks verify explicit exclusions and complete delivery. They do not measure human satisfaction. {discoveries?'The baseline uses the same Qloo response conditioned on the confirmed artist and known favorites, with the same exclusion guard. Known favorites stay outside both recommendation lists.':'The baseline receives the same favorites and exclusions, with favorites first and Qloo order as its tie breaker.'}</p>{Object.entries(results).map(([profile,row])=><div className={styles.cinemaProfile} key={profile}><h3>PROFILE {profile}</h3><p>{row.eligible_count} eligible movies · {row.excluded_removed.length} movies excluded from the eligible catalog.{discoveries?` ${row.known_favorite_count??0} known favorites used as inputs only.`:''}</p><p>{row.selection_changed?'DELIVERY CHANGED: explicit exclusions replaced movies in the raw top five.':'RAW TOP FIVE ALREADY CONFORMED: the exclusion guard kept the same five.'}</p><div className={styles.rankings}>{[['RAW MODEL TOP FIVE',row.raw_ranking.slice(0,5)],['DELIVERED FIVE',row.delivered],[discoveries?'SAME INPUTS QLOO BASELINE':'SAME PREFERENCES BASELINE',row.baseline_delivered]].map(([title,ids])=><div key={title as string}><h3>{title as string}</h3><ol>{(ids as string[]).map((id,index)=><li key={id}><span className={styles.position}>{String(index+1).padStart(2,'0')}</span><span>{names.get(id)??id}</span></li>)}</ol></div>)}</div><details className={styles.details}><summary>INSPECT PREFERENCE AND DELIVERY IDENTIFIERS</summary><pre>{JSON.stringify({preferences_sha256:row.preferences_sha256,intent_sha256:row.intent_sha256,raw_ranking_sha256:row.raw_ranking_sha256,delivery_sha256:row.delivery_sha256},null,2)}</pre></details></div>)}</section>;
}
