'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import styles from './individual-screening.module.css';
import {CinemaPreferencesEditor, CinemaResults, type PreferencePair, emptyPreferences} from './cinema-preferences';
import {CinemaIdentityPicker, CinemaConfirmedIdentities, type IdentityCandidates, type IdentityPair, type IdentityQueries, type IdentitySelection} from './cinema-identities';

type Artists={A:string;B:string};
type Movie={entity_id:string;name:string;release_year:number};
type Capability={cinema_preferences_supported?:boolean;cinema_identity_confirmation_supported?:boolean;cinema_discoveries_supported?:boolean;configured:boolean;execution_enabled:boolean;simulation_only:boolean;admissions_blocked?:boolean;minimum_model_interval_seconds?:number;operator_mode?:'local'|'groq';provider?:string;default_artists?:Artists;model?:string;catalog?:Movie[];remaining_plans?:number;remaining_executions?:number;jobs:{job_id:string;status:string;artists:Artists}[]};
type Trace={requested_profile_sha256:string;transmitted_profile_sha256:string;tool_profile_sha256:string;output_profile_sha256:string;execution_id:string;cache_hit:boolean};
type Repeat={victim:string;before:string[];after:string[];healthy:string[];diagnosis:{diagnosis:string;operation:string};before_trace:Trace;after_trace:Trace};
type Case={fault:string;passing:boolean;checks:Record<string,boolean>;behavioral_recovery_observed_repeats:number};
type Result={preference_gate?:string;cinema_results?:Parameters<typeof CinemaResults>[0]['results'];verification_status:string;provenance:string;causal_gate:string;integration_gate?:string;backend_comparability?:{status:string;observed_decisions:number;system_fingerprints:string[];missing_fingerprint_decisions:number};behavioral_gate:string;cultural_gate:string;release_gate:string;model_attempts:number;qloo_attempts:number;external_service_attested:boolean;frames?:{fault:string;repeats:Repeat[]}[];summary?:{cases:Case[]}};
type Job={preferences?:PreferencePair|null;case_protocol?:string;identity_candidates?:IdentityCandidates;identity_queries?:IdentityQueries;identity_receipt_sha256?:string;chosen_identities?:IdentityPair;declared_faults?:number;job_id:string;status:string;artists:Artists;model:string;operator_mode:'local'|'groq';model_load_requests:number;model_metadata_requests:number;plan_sha256:string;catalog_sha256:string;simulation_only:boolean;maximum_qloo_requests:number;maximum_model_decisions:number;saved_provider_samples:number;saved_model_packets:number;error_class:string|null;result:Result|null};
const labels:Record<string,string>={'cache-omits-profile':'PROFILE MISSING FROM CACHE KEY','stale-profile':'STALE REQUEST PROFILE','wrong-tool-profile':'WRONG QLOO PROFILE'};
const failureMessages:Record<string,string>={
  DiscoveryRateLimitError:'The model provider reached a rate limit. This case stopped and retained its partial evidence.',
  DiscoveryCredentialsError:'The model provider rejected the server credentials. The owner must review the server configuration.',
  DiscoveryRequestRejectedError:'The model provider rejected this request. This case stopped and retained its evidence.',
  DiscoveryServiceError:'The remote model service could not complete this request.',
  DiscoveryNetworkError:'The server could not complete the secure connection to the model provider.',
  AgentError:'The model decision could not be accepted. The saved error does not identify the exact provider cause.'
};
const busy=(job:Job|null)=>!!job&&['STARTED','STARTED_IDENTITY_SEARCH','STARTED_CONFIRMED_CAPTURE','VERIFYING'].includes(job.status);
class RejectedRequest extends Error{constructor(message:string,public status:number){super(message)}}
async function get<T>(path:string,signal?:AbortSignal):Promise<T>{const response=await fetch(path,{signal,cache:'no-store',credentials:'same-origin'});const value=await response.json();if(!response.ok)throw new RejectedRequest(value.error??'The case evidence could not be read.',response.status);return value;}
async function post<T>(path:string,body:unknown,csrf?:string):Promise<T>{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json',...(csrf?{'X-AffinityQA-CSRF':csrf}:{})},body:JSON.stringify(body),cache:'no-store',credentials:'same-origin'});const value=await response.json();if(!response.ok)throw new RejectedRequest(value.error??'The operation could not be admitted.',response.status);return value;}

export function IndividualScreening({publicMode=false}:{publicMode?:boolean}={}){
  const [cap,setCap]=useState<Capability|null>(null),[artists,setArtists]=useState<Artists>({A:'',B:''}),[job,setJob]=useState<Job|null>(null);
  const [cinemaMode,setCinemaMode]=useState(true),[preferences,setPreferences]=useState<PreferencePair>(()=>({A:emptyPreferences(),B:emptyPreferences()}));
  const [error,setError]=useState(''),[pending,setPending]=useState(false),[fault,setFault]=useState(0),[repeat,setRepeat]=useState(0),[reload,setReload]=useState(0);
  const [csrf,setCsrf]=useState(''),[serverReady,setServerReady]=useState<boolean|null>(null),[uncertain,setUncertain]=useState(false);
  const [identitySelection,setIdentitySelection]=useState<IdentitySelection&{scope:string}>({scope:'',A:'',B:''});
  const mounted=useRef(true),inFlight=useRef(false);
  const base=publicMode?'/api/demo/cases':'/api/individual';
  const canAccessJob=!publicMode||!!csrf&&!!cap?.jobs.some(item=>item.job_id===job?.job_id);
  const caseBusy=busy(job)&&canAccessJob;
  const identityScope=`${job?.job_id??''}:${job?.identity_receipt_sha256??''}`;
  const selectedIdentities:IdentitySelection=identitySelection.scope===identityScope?identitySelection:{A:'',B:''};
  useEffect(()=>{setIdentitySelection({scope:identityScope,A:'',B:''})},[identityScope]);
  const handleMissingSession=useCallback((e:unknown)=>{
    if(!publicMode||!(e instanceof RejectedRequest)||e.status!==404)return false;
    setCsrf('');setCap(null);setUncertain(true);
    setError('Your review session has expired or is unavailable. Open a session to continue. Any admitted case stays on the server; opening a session does not repeat it.');
    return true;
  },[publicMode]);
  useEffect(()=>{mounted.current=true;return()=>{mounted.current=false}},[]);
  useEffect(()=>{const controller=new AbortController();if(publicMode&&!csrf){get<{new_cases_configured?:boolean}>('/healthz',controller.signal).then(value=>setServerReady(value.new_cases_configured===true)).catch(e=>{if(e.name!=='AbortError')setError(e.message)});}else{get<Capability>(base+'/capabilities',controller.signal).then(value=>{setCap(value);setArtists(previous=>previous.A||previous.B?previous:value.default_artists??previous)}).catch(e=>{if(e.name!=='AbortError'&&!handleMissingSession(e))setError(e.message)});}return()=>controller.abort()},[reload,csrf,publicMode,base,handleMissingSession]);
  useEffect(()=>{if(!caseBusy)return;const controller=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=()=>{timer=setTimeout(()=>{get<Job>(base+'/jobs/'+job!.job_id,controller.signal).then(value=>{setJob(value);setError('');if(busy(value))poll();else setReload(n=>n+1)}).catch(e=>{if(e.name!=='AbortError'){setError('Progress is unavailable. The job may still be running; check its current status before another action.');setUncertain(true);}})},publicMode?3000:1500)};poll();return()=>{controller.abort();clearTimeout(timer)}},[job?.job_id,job?.status,base,publicMode,caseBusy]);
  async function action(run:()=>Promise<Job>,mutation=false){if(inFlight.current)return;inFlight.current=true;setPending(true);setError('');try{const value=await run();if(mounted.current){setJob(value);setFault(0);setRepeat(0);setReload(n=>n+1)}}catch(e){if(mounted.current){setError(e instanceof Error?e.message:'The operation failed.');if(mutation&&(!(e instanceof RejectedRequest)||e.status>=500))setUncertain(true);}}finally{inFlight.current=false;if(mounted.current)setPending(false)}}
  async function connect(){if(inFlight.current)return;inFlight.current=true;setPending(true);setError('');try{const value=await post<{schema_version:number;csrf_token:string;expires_utc:string}>(base+'/session',{});if(value.schema_version!==1||!/^[a-f0-9]{64}$/.test(value.csrf_token))throw Error('Session response could not be verified.');if(mounted.current){setCap(null);setCsrf(value.csrf_token);setUncertain(false);}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Session access unavailable.')}finally{inFlight.current=false;if(mounted.current)setPending(false)}}
  async function checkStatus(){if(inFlight.current)return;inFlight.current=true;setPending(true);try{if(publicMode&&!csrf){setReload(n=>n+1);return;}let value:Capability;try{value=await get<Capability>(base+'/capabilities');}catch(e){if(mounted.current&&handleMissingSession(e))return;throw e;}const selectedId=job&&value.jobs.some(item=>item.job_id===job.job_id)?job.job_id:value.jobs.at(-1)?.job_id;const latest=selectedId?await get<Job>(base+'/jobs/'+selectedId):null;if(mounted.current){setCap(value);if(latest)setJob(latest);setUncertain(false);setError('');}}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Status unavailable.')}finally{inFlight.current=false;if(mounted.current)setPending(false)}}
  const cinemaEnabled=cinemaMode&&cap?.cinema_preferences_supported===true;
  const identityEnabled=cinemaEnabled&&cap?.cinema_identity_confirmation_supported===true;
  const discoveryEnabled=identityEnabled&&cap?.cinema_discoveries_supported===true;
  const discoveryJob=job?.case_protocol==='cinema-confirmed-discovery-v1'||job?.case_protocol==='cinema-confirmed-discovery-v2';
  const eligibleChoices=!discoveryEnabled||(['A','B'] as const).every(profile=>(cap?.catalog??[]).filter(movie=>!preferences[profile].favorite_entity_ids.includes(movie.entity_id)&&!preferences[profile].excluded_entity_ids.includes(movie.entity_id)).length>=5);
  const identityJob=discoveryJob||job?.case_protocol==='cinema-confirmed-identity-v1';
  const cinemaJob=identityJob||job?.case_protocol==='cinema-preferences-v1';
  const awaitingIdentities=identityJob&&job?.status==='AWAITING_IDENTITY_CONFIRMATION';
  const identityWorkflow=identityJob||(!job&&identityEnabled);
  const identityCandidates=job?.identity_candidates??{A:[],B:[]};
  const identityQueries=job?.identity_queries??job?.artists??artists;
  const selectedA=identityCandidates.A.find(candidate=>candidate.entity_id===selectedIdentities.A);
  const selectedB=identityCandidates.B.find(candidate=>candidate.entity_id===selectedIdentities.B);
  const canConfirmIdentities=awaitingIdentities&&!!selectedA&&!!selectedB&&selectedA.entity_id!==selectedB.entity_id&&!!job?.identity_receipt_sha256&&!pending&&!uncertain&&canAccessJob&&cap?.execution_enabled===true;
  function invalidatePlan(){setIdentitySelection({scope:identityScope,A:'',B:''});if(job?.status==='PLANNED'||awaitingIdentities)setJob(null)}
  function chooseIdentity(profile:'A'|'B',entityId:string){setIdentitySelection(previous=>({...((previous.scope===identityScope)?previous:{scope:identityScope,A:'',B:''}),[profile]:entityId}))}
  const result=job?.result, cases=result?.summary?.cases??[], selected=cases[fault], frame=result?.frames?.[fault]?.repeats[repeat];
  return <section className={styles.root} aria-labelledby="individual-title">
    <header className={styles.header}><div><span className={styles.eyebrow}>NEW INDIVIDUAL CASE</span><h1 id="individual-title">NEW INDIVIDUAL CASE</h1></div><p>{identityWorkflow?'Choose two musical interests and, optionally, film tastes. Review the plan, find your artists, then confirm their identities before the model review begins.':'Choose two musical interests and, optionally, film tastes. Inspect the execution plan and review the saved results. New model and Qloo calls begin only when you start the reviewed plan.'}</p></header>
    <ol className={styles.workflow} data-steps={identityWorkflow?4:3} aria-label="Individual case workflow"><li data-current={!job}><span>01</span><strong>REVIEW THE PLAN</strong><small>No provider calls</small></li><li data-current={job?.status==='PLANNED'||job?.status==='STARTED_IDENTITY_SEARCH'||(!identityWorkflow&&caseBusy)}><span>02</span><strong>{identityWorkflow?'FIND ARTISTS':'START THE REVIEW'}</strong><small>{identityWorkflow?'2 Qloo searches · 0 model calls':'Explicit execution admission'}</small></li>{identityWorkflow&&<li data-current={awaitingIdentities||job?.status==='STARTED_CONFIRMED_CAPTURE'||job?.status==='VERIFYING'}><span>03</span><strong>CONFIRM & REVIEW</strong><small>2 Qloo insights · 2 model calls</small></li>}<li data-current={!!result}><span>{identityWorkflow?'04':'03'}</span><strong>INSPECT THE EVIDENCE</strong><small>Checks, rankings and receipt</small></li></ol>
    {error&&<div className={styles.warning} role="alert"><p>{error}</p>{uncertain&&<p>The response is uncertain. Check saved status; the server keeps any admitted execution and never retries it automatically.</p>}<button onClick={()=>void checkStatus()} disabled={pending}>CHECK CURRENT STATUS</button></div>}
    {publicMode&&!csrf?<div className={styles.notice}><h2>{serverReady===null?'CHECKING PUBLIC CASE SETUP':serverReady?'OPEN YOUR REVIEW SESSION':'NEW CASES AWAIT SERVER SETUP'}</h2><p>A private browser session keeps your interests and cases separate from other visitors. Opening it makes no Qloo or model requests.</p><button className={styles.primary} disabled={pending||serverReady!==true} onClick={()=>void connect()}>OPEN OR RESTORE MY SESSION</button></div>:!cap?<p role="status">CHECKING CASE CONFIGURATION…</p>:!cap.configured?<div className={styles.notice}><h2>SERVER SETUP REQUIRED</h2><p>The server needs an explicit movie catalog and model configuration before it can prepare new cases. Existing recorded screening remains available.</p><p>New execution is disabled. No Qloo or model request has started.</p></div>:<>
      {cap.admissions_blocked&&<div className={styles.warning}><h2>NEW ADMISSIONS PAUSED</h2><p>Storage requires the owner's inspection. Saved cases remain readable.</p></div>}
      {!cap.execution_enabled&&<div className={styles.notice}><h2>PREPARATION ONLY</h2><p>You can inspect a new plan. Execution is disabled in the server configuration; preparing a plan makes no Qloo or model requests.</p></div>}
      {(cap.simulation_only||job?.simulation_only)&&<div className={styles.warning}><h2>SIMULATION ONLY</h2><p>These adapters provide synthetic observations. Results do not prove Qloo access or actual model behavior.</p></div>}
      {cap.cinema_preferences_supported&&<div className={styles.modePicker} role="group" aria-label="Choose case type"><button type="button" aria-pressed={cinemaMode} disabled={pending||caseBusy} onClick={()=>{setCinemaMode(true);invalidatePlan()}}>FILM PREFERENCES<small>Two recommendations - favorites and exclusions</small></button><button type="button" aria-pressed={!cinemaMode} disabled={pending||caseBusy} onClick={()=>{setCinemaMode(false);invalidatePlan()}}>PROFILE INTEGRITY<small>39 decisions - three controlled faults</small></button></div>}
      <div className={styles.setup}><div className={styles.sectionHeading}><h2>YOUR MUSICAL INTERESTS</h2><span>Prepare a plan before execution</span></div><form className={styles.form} onSubmit={event=>{event.preventDefault();if(!eligibleChoices)return;void action(()=>post<Job>(base+'/plans',{artists,...(cinemaEnabled?{preferences}:{}),...(identityEnabled?{confirm_identities:true}:{}),...(discoveryEnabled?{discover_new_movies:true}:{})},publicMode?csrf:undefined),true)}}>
        <label>MUSICAL INTEREST A<input required maxLength={300} placeholder="Enter an artist or musical interest" value={artists.A} onChange={e=>{setArtists({...artists,A:e.target.value});invalidatePlan()}} disabled={pending||caseBusy}/></label>
        <label>MUSICAL INTEREST B<input required maxLength={300} placeholder="Enter an artist or musical interest" value={artists.B} onChange={e=>{setArtists({...artists,B:e.target.value});invalidatePlan()}} disabled={pending||caseBusy}/></label>
        {cinemaEnabled&&<CinemaPreferencesEditor catalog={cap.catalog??[]} artists={artists} preferences={preferences} discoveries={discoveryEnabled} disabled={pending||caseBusy} onChange={value=>{setPreferences(value);invalidatePlan()}}/>}
        <button className={styles.primary} disabled={!eligibleChoices||pending||uncertain||caseBusy||cap.admissions_blocked||cap.remaining_plans===0}>REVIEW A NEW PLAN</button>
      </form></div>
      <details className={styles.details}><summary>INSPECT THE {cap.catalog?.length??0}-MOVIE CATALOG AND {cap.operator_mode==='groq'?'CLOUD':'LOCAL'} MODEL</summary><p>{cap.model} · {cap.remaining_executions} execution admissions remaining in this storage.</p>{cap.operator_mode==='groq'&&<p>Groq runs the model remotely. This case does not load a model on your computer.</p>}<ul>{cap.catalog?.map(movie=><li key={movie.entity_id}>{movie.name} ({movie.release_year})</li>)}</ul></details>
      {publicMode&&typeof cap.minimum_model_interval_seconds==='number'&&<p className={styles.small}>The configured interval is {cap.minimum_model_interval_seconds} seconds between model admissions. The {cinemaEnabled?'two-decision preference review':'39-decision integrity protocol'} needs at least {((cinemaEnabled?1:38)*cap.minimum_model_interval_seconds/60).toFixed(1)} minutes of scheduled spacing, plus provider and verification time.</p>}
    </>}
    {job&&<section className={styles.job} aria-labelledby="job-title"><div className={styles.jobHeader}><h2 id="job-title">{job.status==='PLANNED'?'YOUR EXECUTION PLAN':'YOUR INDIVIDUAL CASE'}</h2><strong className={styles.jobStatus} role="status" data-state={job.status}>{!canAccessJob?'LAST KNOWN STATUS: ':''}{job.status.replaceAll('_',' ')}</strong></div>
      {!canAccessJob&&<div className={styles.notice}><h3>PREVIOUS SESSION SNAPSHOT</h3><p>This view retains the last status received. The current session cannot read, start or download this case. Opening a session does not cancel or repeat an admitted capture.</p></div>}
      <p className={styles.artists}>{job.artists.A} <span aria-hidden="true">↔</span> {job.artists.B}</p>
      <div className={styles.stats}><div><strong>{job.maximum_qloo_requests}</strong><span>MAXIMUM QLOO REQUESTS</span></div><div><strong>{job.maximum_model_decisions}</strong><span>MAXIMUM MODEL DECISIONS</span></div><div><strong>{job.declared_faults??3}</strong><span>DECLARED FAULTS</span></div></div>
      {cinemaJob&&(job.status==='PLANNED'||awaitingIdentities)&&<div className={styles.notice}><h3>REVIEWED FILM PREFERENCES</h3><p>{discoveryJob?'Known favorites guide Qloo and the model and will not be recommended again.':'Favorites guide the model.'} Exclusions are mandatory. The raw model order is preserved, then the first five eligible movies are delivered. This separate review makes no controlled-fault repair claim.</p>{(['A','B'] as const).map(profile=><div key={profile}><h3>PROFILE {profile}</h3><p>Favorites: {job.preferences?.[profile].favorite_entity_ids.map(id=>cap?.catalog?.find(movie=>movie.entity_id===id)?.name??id).join(', ')||'None selected'}</p><p>Avoid: {job.preferences?.[profile].excluded_entity_ids.map(id=>cap?.catalog?.find(movie=>movie.entity_id===id)?.name??id).join(', ')||'None selected'}</p></div>)}</div>}
      {identityJob&&job.chosen_identities&&<CinemaConfirmedIdentities identities={job.chosen_identities} queries={identityQueries}/>}
      {job.status==='PLANNED'?<>
        {identityJob&&<div className={styles.identityBudget}><h3>TWO PHASES · ONE EXECUTION ADMISSION</h3><p>The complete case allows 4 Qloo requests and 2 {job.operator_mode==='groq'?'Groq model calls':'model decisions'}. First: 2 artist searches and no model calls. After your confirmation: 2 Qloo insights requests and the 2 model calls.</p></div>}
        <p>{job.operator_mode==='groq'?'The model runs remotely, with no local model load or metadata requests.':'Execution includes model metadata checks and one model load.'} Each request has one attempt. A failure stops the capture and preserves its partial evidence.</p>
        <button className={styles.primary} disabled={!canAccessJob||pending||uncertain||!cap?.execution_enabled||cap.remaining_executions===0} onClick={()=>void action(()=>post<Job>(base+'/jobs/'+job.job_id+'/execute',{plan_sha256:job.plan_sha256},publicMode?csrf:undefined),true)}>{identityJob?'FIND ARTISTS':`START THIS REVIEWED ${job.operator_mode==='groq'?'CLOUD':'LOCAL'} PLAN`}</button>
        <p className={styles.small}>{job.simulation_only?'This test uses synthetic adapters. It makes no real Qloo or model requests.':identityJob?'This step sends only the two musical queries to Qloo: 2 search requests and 0 Groq or other model calls. You will confirm the returned artists before insights and ranking begin.':job.operator_mode==='groq'?'This button sends the reviewed interests, any film preferences, movie catalog and Qloo context to the remote model when execution is enabled.':'This button starts new Qloo requests and local inference when execution is enabled.'}</p>
      </>:<>
        <div className={styles.progress} aria-live="polite"><p>{job.saved_provider_samples}/{job.maximum_qloo_requests} provider samples saved · {job.saved_model_packets}/{job.maximum_model_decisions} model packets saved</p><progress max={job.maximum_model_decisions} value={job.saved_model_packets} aria-label="Saved model decision packets"/></div>
        {caseBusy&&<p>{job.status==='STARTED_IDENTITY_SEARCH'?'The server is searching for your artists. No model call begins during this phase.':job.status==='STARTED_CONFIRMED_CAPTURE'?'The server is running Qloo insights and ranking with your confirmed artists.':job.status==='VERIFYING'?'The server is auditing the recorded evidence.':'The server is running the admitted capture.'} Closing this page does not cancel the job. Return to this job to inspect its status.</p>}
        {awaitingIdentities&&<>
          <CinemaIdentityPicker candidates={identityCandidates} queries={identityQueries} selection={selectedIdentities} disabled={pending||!canAccessJob||uncertain||!cap?.execution_enabled} groupId={job.job_id} onChange={chooseIdentity}/>
          <div className={styles.identityConfirm}><div><h3>REVIEW YOUR SELECTION</h3><p>{selectedA&&selectedB?<>{selectedA.name} <span aria-hidden="true">↔</span> {selectedB.name}</>:'Choose one artist for each profile to continue.'}</p><p className={styles.small}>Confirmation continues the admission already used by the artist search. It does not require a second execution admission.</p></div>
            <button type="button" className={styles.primary} disabled={!canConfirmIdentities} onClick={()=>{if(!canConfirmIdentities)return;void action(()=>post<Job>(base+'/jobs/'+job.job_id+'/confirm-identities',{plan_sha256:job.plan_sha256,identity_receipt_sha256:job.identity_receipt_sha256,selected_entity_ids:{A:selectedIdentities.A,B:selectedIdentities.B}},publicMode?csrf:undefined),true)}}>CONFIRM ARTISTS & START REVIEW</button>
          </div>
          <p className={styles.small}>{job.simulation_only?'This test continues with synthetic adapters. It makes no real Qloo or model requests.':`This confirmation sends the selected artists to Qloo for 2 insights requests, then sends their Qloo context, reviewed film preferences and movie catalog to ${job.operator_mode==='groq'?'Groq for 2 remote model calls':'the configured model for 2 decisions'}.`}</p>
        </>}
        {['PARTIAL','FAILED','ABANDONED','EVIDENCE_CHANGED'].includes(job.status)&&<div className={styles.warning}><h3>{cinemaJob?'NO COMPLETED PREFERENCE REVIEW':'NO COMPLETED REPAIR CLAIM'}</h3><p>{job.status==='PARTIAL'?'The verifier accepted only the committed partial evidence.':job.status==='ABANDONED'?'The server restarted before a terminal verification was committed.':'Evidence could not be admitted.'} Original files are retained; this job will not execute again.</p>{job.error_class&&<p>{failureMessages[job.error_class]??`Recorded failure: ${job.error_class}`}</p>}</div>}
      </>}
      {result&&<>{result.cinema_results&&<CinemaResults results={result.cinema_results} catalog={cap?.catalog??[]} gate={result.preference_gate??'NOT_EVALUATED'} discoveries={discoveryJob}/>}<div className={styles.gates}>{!cinemaJob&&<><div><span>{result.integration_gate?'CAUSAL ATTRIBUTION':'CAUSAL CHECKS'}</span><strong data-state={result.causal_gate}>{result.causal_gate}</strong></div>{result.integration_gate&&<div><span>INTEGRATION CHECKS</span><strong data-state={result.integration_gate}>{result.integration_gate}</strong></div>}<div><span>OBSERVED BEHAVIOR</span><strong data-state={result.behavioral_gate}>{result.behavioral_gate.replaceAll('_',' ')}</strong></div></>}<div><span>CULTURAL QUALITY</span><strong data-state={result.cultural_gate}>{result.cultural_gate.replaceAll('_',' ')}</strong></div></div><p>{result.verification_status.replaceAll('_',' ')} · {result.provenance.replaceAll('_',' ')}. {result.qloo_attempts} recorded provider attempts; {result.model_attempts} recorded ranking attempts. Release remains {result.release_gate.toLowerCase()}.</p>
        {result.causal_gate==='INCONCLUSIVE'&&result.backend_comparability&&result.backend_comparability.status!=='STABLE_KNOWN'&&<div className={styles.warning}><h3>CAUSAL ATTRIBUTION INCONCLUSIVE</h3><p>Profile integrity was restored and integration checks passed, but the backend fingerprint varied or was absent across decisions. Observed recovery cannot be causally attributed to the repair.</p></div>}
        {cases.length>0&&<><div className={styles.tabs} role="group" aria-label="Inspect declared fault">{cases.map((value,index)=><button key={value.fault} aria-pressed={fault===index} onClick={()=>{setFault(index);setRepeat(0)}}>{labels[value.fault]??value.fault}</button>)}</div><h3>{result.integration_gate?(selected?.passing?'INTEGRATION CHECKS PASSED':'INTEGRATION CHECKS FAILED'):(selected?.passing?'CAUSAL CHECKS PASSED':'CAUSAL CHECKS FAILED')}</h3><p>{selected?.behavioral_recovery_observed_repeats}/3 repeats showed observed behavioral recovery for this fault.</p><ul className={styles.checks}>{Object.entries(selected?.checks??{}).map(([name,passed])=><li key={name}><span>{name.replaceAll('_',' ').toUpperCase()}</span><strong data-pass={passed}>{passed?'PASS':'FAIL'}</strong></li>)}</ul>
          {frame&&<><label className={styles.repeat}>INSPECT REPEAT<select value={repeat} onChange={e=>setRepeat(Number(e.target.value))}>{[0,1,2].map(n=><option key={n} value={n}>REPEAT {n+1}</option>)}</select></label><p>Diagnosis: {frame.diagnosis.diagnosis} · Repair: {frame.diagnosis.operation} · affected profile {frame.victim}</p><div className={styles.rankings}>{[['BEFORE REPAIR',frame.before],['AFTER REPAIR',frame.after],['HEALTHY REFERENCE',frame.healthy]].map(([title,films])=><div key={title as string}><h3>{title as string}</h3><ol>{(films as string[]).map((name,index)=><li key={index}><span className={styles.position}>{String(index+1).padStart(2,'0')}</span><span>{name}</span></li>)}</ol></div>)}</div><details className={styles.details}><summary>INSPECT THE BEFORE / AFTER PROFILE TRACE</summary><pre>{JSON.stringify({before:frame.before_trace,after:frame.after_trace},null,2)}</pre></details></>}
        </>}
        {canAccessJob&&<a className={styles.link} href={base+'/jobs/'+job.job_id+'/verification'} download>{publicMode?'DOWNLOAD SELECTED VERIFICATION':'DOWNLOAD VERIFICATION RECEIPT'}</a>}<p className={styles.small}>Verification checks recorded-file consistency and independently recalculates the declared checks. It does not cryptographically attest the external services or validate cultural quality.</p>
      </>}
      <details className={styles.details}><summary>INSPECT PLAN IDENTIFIERS</summary><dl><dt>JOB</dt><dd>{job.job_id}</dd><dt>PLAN SHA-256</dt><dd>{job.plan_sha256}</dd><dt>CATALOG SHA-256</dt><dd>{job.catalog_sha256}</dd>{job.identity_receipt_sha256&&<><dt>ARTIST SEARCH RECEIPT SHA-256</dt><dd>{job.identity_receipt_sha256}</dd></>}</dl></details>
    </section>}
    {!!cap?.jobs.length&&<section className={styles.history}><h2>{publicMode?'YOUR SAVED CASES':'RECENT INDIVIDUAL CASES'}</h2><p>Opening a job reads its status and existing evidence. It does not start new work.</p><ul>{cap.jobs.map(item=><li key={item.job_id}><button disabled={pending} onClick={()=>void action(()=>get<Job>(base+'/jobs/'+item.job_id))}>{item.artists.A} / {item.artists.B} — {item.status.replaceAll('_',' ')}</button><small>{item.job_id}</small></li>)}</ul></section>}
  </section>;
}
