import type {IndividualStudy} from '../lib/review';
import {Pill,Arrow} from './primitives';

const signed=(v:number)=>(v>=0?'+':'')+v.toFixed(6);
export function IndividualDevelopment({study}:{study:IndividualStudy}){
  return <section className="context-archive"><div className="archive-section-title"><div><span className="eyebrow">PREVIOUS / IDENTITY-CHECKED SIGNAL STUDY</span><h2>Check the identity.<br/><em>Then trust the signal.</em></h2></div><p>This signal study excludes original profiles and duplicate related artists by identifier, name and returned aliases. All fourteen known pairs remain. The repair still fails the release checks.</p></div>
    <div className="context-totals"><span><strong>{study.best_passes} / {study.denominator}</strong> Known pairs pass all controls</span><span><strong>{study.available_projections} / {study.total_projections}</strong> Related artists with usable affinity</span><span><strong>{study.candidate_count}</strong> Declared variants checked</span><span><strong>{study.new_qloo_requests}</strong> Qloo requests · zero model calls</span></div>
    <Pill tone="coral">Development rejected · no new validation</Pill>
    <div className="repair-reasons"><span className="eyebrow">HISTORICAL EVIDENCE CORRECTION</span><p>Qloo returned Ryuichi Sakamoto as 坂本龍一 under another identifier. The earlier artist-view studies included that original identity; their 13 / 14 result needs this qualification. Those records remain intact. The latest movie-only validation is unaffected and remains 4 / 6, FAIL.</p></div>
    <p>One artist, Elvis Costello &amp; The Attractions, returned no affinity values. The first attempt stopped after seven requests. A recorded coverage amendment completed the original 68-request budget without retries or invented scores. David Byrne uses two available related artists; the other profiles use three.</p>
    <details className="integrity-details"><summary><span className="eyebrow">ALL FOURTEEN PAIRS</span><strong>Inspect the identity-checked result.</strong></summary><p>The first of two tied development variants is shown. It is not deployed. Related-artist data was captured once and reused across existing model repeats; this does not establish provider repeat stability.</p>{study.cases.map(c=><div className="candidate-checks" key={c.pair_id}><strong>{c.artists.A} / {c.artists.B}</strong><Pill tone={c.passing?'neutral':'coral'}>{c.passing?'PASS':'FAIL'}</Pill>{!c.passing&&<div>{(['baseline','neutral_graph'] as const).flatMap(v=>(['A','B'] as const).filter(p=>c.comparisons[v][p].min < -1e-12).map(p=><p key={v+p}>{c.artists[p]}: {signed(c.comparisons[v][p].min)} against {v==='baseline'?'the original agent':'pooled context'}.</p>))}{!c.checks.benefit_beyond_neutral&&<p>Pair gain over pooled context: {signed(c.minimum_pair_mean_delta.neutral_graph)}; required +0.020000.</p>}</div>}</div>)}<p className="metric-note">All 28 variants were recalculated from saved decisions and raw Qloo records. No acceptance threshold changed and no case was removed.</p><a className="button outline" href="/api/individual-context" target="_blank" rel="noreferrer">Open verified identity study <Arrow diagonal/></a></details>
  </section>;
}
