import {useState} from 'react';
import type {Snapshot} from '../lib/review';
import {isMixed,signed,serial} from '../lib/review';
import {Arrow,PairArtwork,Pill} from './primitives';

export function Library({data,openCase}:{data:Snapshot;openCase:(id:string)=>void}){
  const [query,setQuery]=useState(''),[filter,setFilter]=useState('all');
  const cases=data.cases.filter(c=>(filter==='all'||(filter==='mixed'?isMixed(c):!isMixed(c)))&&[c.artists.A,c.artists.B].join(' ').toLocaleLowerCase().includes(query.trim().toLocaleLowerCase()));
  return <section className="section-page"><div className="page-heading"><div><span className="eyebrow">03 / CASE LIBRARY · HISTORICAL STUDY</span><h1>Different tastes.<br/><em>The same test.</em></h1></div><p>Six pairs from the earlier cache study, preserved with every outcome. The current profile-integrity cases are in the Screening room.</p></div><div className="library-toolbar"><div className="filter-group" role="group" aria-label="Filter cases">{[['all','All cases',data.case_count],['gain','Consistent gain',data.counts.OBSERVED_AGREEMENT_IMPROVEMENT??0],['mixed','Mixed result',data.counts.MIXED??0]].map(([id,label,count])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(String(id))}>{label}<span>{count}</span></button>)}</div><label className="search-field"><svg viewBox="0 0 24 24" width="18" height="18" fill="none" aria-hidden="true"><circle cx="10" cy="10" r="6" stroke="currentColor" strokeWidth="1.5"/><path d="m15 15 5 5" stroke="currentColor" strokeWidth="1.5"/></svg><input type="search" aria-label="Search artist names" placeholder="Find an artist…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="result-count" role="status">{cases.length} of {data.case_count} cases</div><div className="case-grid">{cases.map(item=>{const index=data.cases.indexOf(item);return <button className="case-card" key={item.id} onClick={()=>openCase(item.id)} aria-label={'Review '+item.artists.A+' and '+item.artists.B}><div className="case-art-wrap"><PairArtwork item={item} index={index}/><Pill tone={isMixed(item)?'coral':'paper'}>{isMixed(item)?'Mixed result':'Consistent gain'}</Pill></div><div className="case-card-body"><span className="eyebrow">CASE {serial(index)} / MUSIC → MOVIES</span><h2>{item.artists.A}<span>to</span>{item.artists.B}</h2><div className="case-card-footer"><div><span>Paired agreement change</span><strong>{signed(item.delta.min)} to {signed(item.delta.max)}</strong></div><span className="circle-arrow"><Arrow diagonal/></span></div></div></button>})}</div>{cases.length===0&&<div className="empty-state"><h2>No matching cases.</h2><p>Try another artist or reset the filters.</p><button className="button outline" onClick={()=>{setQuery('');setFilter('all')}}>Show all six cases <Arrow/></button></div>}<p className="library-footnote">The full denominator stays visible. Paired changes compare the mean agreement of two profiles; they are not satisfaction percentages or independent user trials.</p></section>;
}
