import type {OrderingStudy} from '../lib/review';
import {Pill,Arrow} from './primitives';

export function OrderingDevelopment({study}:{study:OrderingStudy}){
  return <section className="context-archive"><div className="archive-section-title"><div><span className="eyebrow">HISTORICAL / DEVELOPMENT · IDENTITY QUALIFICATION</span><h2>A recorded result.<br/><em>An identity flaw found later.</em></h2></div><p>The recorded arithmetic gives 13 of 14 known pairs, but the artist context included Ryuichi Sakamoto under another name and identifier. This result is retained with an integrity qualification. The separate identity-checked signal study recorded 12 of 14; current supervised development is shown above.</p></div>
    <div className="context-totals"><span><strong>{study.best_passes} / {study.denominator}</strong> Historical arithmetic · alias overlap</span><span><strong>{study.discrete_candidates}</strong> Declared candidate variants</span><span><strong>{study.calibration_intervals}</strong> Scalar intervals checked</span><span><strong>{study.new_qloo_requests}</strong> Additional Qloo requests</span></div>
    <Pill tone="coral">Historical rejection · identity overlap found</Pill><p>PJ Harvey / Bruno Mars still fails the loss and pooled-context benefit checks. The tested ordering variants did not resolve the conflict across all profiles. No threshold was relaxed and no failed pair was removed.</p>
    <details className="integrity-details"><summary><span className="eyebrow">ALL FOURTEEN PAIRS</span><strong>Inspect the best observed variant.</strong></summary><p>One of two tied development variants is shown. This candidate is not approved or deployed. Every pair has already been used during development.</p>{study.cases.map(c=><div className="candidate-checks" key={c.pair_id}><strong>{c.artists.A} / {c.artists.B}</strong><Pill tone={c.passing?'neutral':'coral'}>{c.passing?'PASS':'FAIL'}</Pill>{!c.passing&&<p>PJ Harvey: {c.comparisons.neutral_graph.A.min.toFixed(6)} against pooled context. Pair gain: +{c.minimum_pair_mean_delta.neutral_graph.toFixed(6)}; required +0.020000.</p>}</div>)}<p className="metric-note">No new model decisions or evaluation references were requested. All 66 discrete variants and 429 intervals were independently recalculated from recorded evidence.</p><a className="button outline" href="/api/ordering-development" target="_blank" rel="noreferrer">Open verified development record <Arrow diagonal/></a></details>
  </section>;
}
