'use client';
import {useEffect,useRef,useState} from 'react';
import {WorkspaceShell} from './workspace-shell';
import modeStyles from './screening-mode.module.css';
import styles from './causal-screening.module.css';
import {IndividualScreening} from './individual-screening';

type Film={position:number;title:string;year:number};
type Trace={requested_profile_sha256:string;transmitted_profile_sha256:string;tool_profile_sha256:string;output_profile_sha256:string;cache_hit:boolean};
type Identity=Record<Exclude<keyof Trace,'cache_hit'>,string>;
type Pair={pair_id:string;artists:{A:string;B:string};split:string;faults:string[]};
type Summary={schema_version:1;status:string;run_id?:string;notice:string;causal_gate:string;cultural_gate:string;release_gate:string;passing?:number;denominator?:number;source_model_calls?:number;source_qloo_requests?:number;observed_repeat_recoveries?:number;noise_barrier?:number;policy_sha256?:string;receipt_sha256?:string;pairs:Pair[];historical_quality?:{development:{passing:number;denominator:number;gate:string};independent:{passing:number;denominator:number;gate:string}}};
type Replay={status:'PASS'|'FAIL';source:'recorded-local-llm-replay';new_model_calls:0;new_qloo_calls:0;recorded_decision_dispatches:number;diagnosis:string;repair:string;checks:Record<string,boolean>;before:Film[];after:Film[];healthy:Film[];trace:Trace;repaired_trace:Trace;notice:string;run_id:string;pair_id:string;fault:string;repeat:number;requested_artist:string;identity_before:Identity;identity_after:Identity};
const stages=['Detect','Diagnose','Repair','Verify'] as const;
const names:Record<string,string>={'cache-omits-profile':'Profile missing from cache key','stale-profile':'Stale profile passed to agent','wrong-tool-profile':'Qloo context bound to wrong profile'};
const readable=(s:string)=>s.replaceAll('_',' ').replaceAll('-',' ');

const boundaries=[['requested_profile_sha256','Requested taste'],['tool_profile_sha256','Qloo context'],['transmitted_profile_sha256','Agent input'],['output_profile_sha256','Decision associated profile']] as const;
const checkNames=['supported_diagnosis','repair_applied','profile_integrity_restored','decision_redispatched','matches_recorded_healthy','legitimate_cache_reuse'];
function Films({label,rows,artist}:{label:string;rows:Film[];artist:string}){return <section className={styles.films}><span className={styles.label}>{label}</span><h4>{artist}</h4><ol>{rows.map(f=><li key={f.position}><span className={styles.position}>{String(f.position).padStart(2,'0')}</span><span>{f.title}<small>{f.year}</small></span></li>)}</ol></section>}
function Binding({title,trace,identity}:{title:string;trace:Trace;identity:Identity}){return <section className={styles.binding} aria-label={title}><h3>{title}</h3><ol>{boundaries.map(([key,label])=><li key={key} data-mismatch={trace[key]!==trace.requested_profile_sha256}><span>{label}</span><strong>{identity[key]}</strong>{trace[key]!==trace.requested_profile_sha256&&<small>Different from requested profile</small>}</li>)}</ol></section>}
function TraceView({title,trace,identity}:{title:string;trace:Trace;identity:Identity}){return <details className={styles.trace}><summary>{title}<span>Inspect verified names & profile fingerprints ↗</span></summary><dl>{boundaries.map(([key,label])=><div key={key}><dt>{label}</dt><dd><strong>{identity[key]}</strong><details><summary>Profile fingerprint</summary><code>{trace[key]}</code></details></dd></div>)}<div><dt>Cache reused</dt><dd>{trace.cache_hit?'Yes':'No'}</dd></div></dl></details>}

const publicItems=[{id:'recorded',label:'Recorded repair',icon:'recorded' as const},{id:'new',label:'New individual case',icon:'new' as const}];

export function PublicScreening(){
  const [mode,setMode]=useState('recorded');
  const [summary,setSummary]=useState<Summary|null>(null),[error,setError]=useState(''),[refresh,setRefresh]=useState(0);
  const [pairIndex,setPairIndex]=useState(0),[fault,setFault]=useState('cache-omits-profile'),[repeat,setRepeat]=useState(1),[stage,setStage]=useState<typeof stages[number]>('Detect');
  const [result,setResult]=useState<Replay|null>(null),[busy,setBusy]=useState(false);const active=useRef<AbortController|null>(null);
  useEffect(()=>{const controller=new AbortController();setError('');setSummary(null);fetch('/api/demo/summary',{cache:'no-store',signal:controller.signal}).then(async r=>{if(!r.ok)throw Error('The recorded demo is unavailable. Please try again.');const data=await r.json();if(data.schema_version!==1||!Array.isArray(data.pairs))throw Error('Unverified demo format.');setSummary(data);}).catch(e=>{if(e.name!=='AbortError')setError(e.message)});return()=>controller.abort()},[refresh]);
  useEffect(()=>()=>active.current?.abort(),[]);
  function reset(){active.current?.abort();setResult(null);setError('');setBusy(false);setStage('Detect')}
  const pair=summary?.pairs[pairIndex];
  async function replay(){
    if(!pair||busy)return;const controller=new AbortController();active.current=controller;setBusy(true);setError('');setResult(null);
    try{const response=await fetch('/api/demo/replay',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pair_id:pair.pair_id,fault,repeat}),signal:controller.signal});const value=await response.json();if(!response.ok)throw Error(response.status===429?'The demo is busy. Please try again shortly.':'Recorded evidence could not be verified. No result approved.');if(value.source!=='recorded-local-llm-replay'||value.new_model_calls!==0||value.new_qloo_calls!==0||value.run_id!==summary?.run_id||value.pair_id!==pair.pair_id||value.fault!==fault||value.repeat!==repeat||value.requested_artist!==(repeat===2?pair.artists.A:pair.artists.B)||!['PASS','FAIL'].includes(value.status)||!value.checks||Object.keys(value.checks).length!==checkNames.length||checkNames.some(key=>typeof value.checks[key]!=='boolean'))throw Error('The replay response could not be verified.');if(!controller.signal.aborted)setResult(value)}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Replay failed.')}finally{if(!controller.signal.aborted)setBusy(false)}
  }
  return <WorkspaceShell publicMode active={mode} title={mode==='recorded'?'RECORDED REPAIR':'NEW INDIVIDUAL CASE'} items={publicItems} onNavigate={id=>setMode(id==='new'?'new':'recorded')}>
    <div className={modeStyles.modeCards} role="group" aria-label="Choose review mode">
      <button type="button" className={modeStyles.modeCard} aria-pressed={mode==='recorded'} onClick={()=>setMode('recorded')}><span className={modeStyles.modeNumber}>01</span><span><strong>EXPLORE A RECORDED REPAIR</strong><small>Saved evidence · 0 new model or Qloo calls</small></span><span className={modeStyles.modeBadge}>RECORDED</span></button>
      <button type="button" className={modeStyles.modeCard} aria-pressed={mode==='new'} onClick={()=>setMode('new')}><span className={modeStyles.modeNumber}>02</span><span><strong>CREATE AN INDIVIDUAL CASE</strong><small>Review a plan first · approximately 14 minutes per run</small></span><span className={modeStyles.modeBadge}>NEW CALLS</span></button>
    </div>
    <div className={modeStyles.modePanel} hidden={mode!=='new'}><IndividualScreening publicMode/></div>
    <div className={modeStyles.modePanel} hidden={mode!=='recorded'}><section className={styles.root+' '+styles.recordedRoot} aria-labelledby="public-demo-title"><header className={styles.header}><div><span className={styles.label}>RECORDED PERSONALIZATION / INTEGRATION REPAIR</span><h1 id="public-demo-title">RECORDED PROFILE REPAIR</h1></div><p>Inspect a profile, cache or tool-routing incident using saved decisions. Follow the requested interest through the fault, correction and verification.</p></header>
    <div className={styles.gates} aria-label="Separate acceptance gates"><div><span>Causal integrity</span><strong data-pass={summary?.causal_gate==='PASS'?true:summary?.causal_gate==='FAIL'?false:undefined} data-state={summary?.causal_gate??'Loading'}>{summary?.causal_gate??'Loading'}</strong></div><div><span>Cultural quality</span><strong data-state={summary?.cultural_gate??'NOT_VALIDATED'}>{summary?.cultural_gate??'NOT_VALIDATED'}</strong></div><div><span>Tested agent release</span><strong data-state={summary?.release_gate??'BLOCKED'}>{summary?.release_gate??'BLOCKED'}</strong></div></div>

    {error&&<p role="alert" className={styles.warning}>{error}</p>}
    {!summary&&error&&<button type="button" className="button outline" onClick={()=>setRefresh(n=>n+1)}>Retry evidence</button>}
    {summary?.status==='UNAVAILABLE'&&<div className={styles.warning}><h2>No verified capture installed.</h2><p>This source preview contains no provider snapshots. Its engineering tests use labeled synthetic fixtures. Install authorized evidence to review a real recorded incident.</p></div>}
    {summary?.status==='COMPLETE'&&pair&&<>

    <div className={styles.selectionPanel}><div className={styles.sectionHeading}><h3>CHOOSE THE INCIDENT</h3><span>Three controlled repeats per case</span></div><div className={styles.selectors}><label>Artist pair<select aria-label="Demo artist pair" value={pairIndex} onChange={e=>{reset();setPairIndex(Number(e.target.value));setFault('cache-omits-profile')}}>{summary.pairs.map((p,i)=><option key={p.pair_id} value={i}>{p.artists.A} / {p.artists.B}</option>)}</select></label><label>Injected incident<select aria-label="Demo fault" value={fault} onChange={e=>{reset();setFault(e.target.value)}}>{pair.faults.map(f=><option value={f} key={f}>{names[f]??readable(f)}</option>)}</select></label><label>Repeated experiment<select aria-label="Demo repeat" value={repeat} onChange={e=>{reset();setRepeat(Number(e.target.value))}}>{[1,2,3].map(n=><option key={n} value={n}>Repeat {n} · request {n===2?pair.artists.A:pair.artists.B} · {n===2?'B → A':'A → B'}</option>)}</select></label></div></div>
    <section className={styles.replay} aria-label="Recorded repair execution"><div className={styles.replayAction}><div><span className={styles.label}>RUN A RECORDED INCIDENT / {pair.split.toUpperCase()} PAIR</span><h2>REPLAY THE REPAIR PATH</h2><p>Saved real-model decisions. No new model or Qloo calls.</p></div><button type="button" disabled={busy} onClick={replay}>{busy?'Executing recorded repair…':'Replay this incident'}</button></div>{busy&&<p role="status">Verifying evidence and executing the pipeline…</p>}{result&&<div aria-live="polite"><h3>Requested taste: {result.requested_artist}</h3><p><strong data-state={result.status}>Replay {result.status}</strong> · {result.recorded_decision_dispatches} recorded dispatches · 0 new model calls · 0 new Qloo calls</p><p>{result.notice}</p><div className={styles.bindings}><Binding title="Before repair / profile route" trace={result.trace} identity={result.identity_before}/><Binding title="After repair / profile route" trace={result.repaired_trace} identity={result.identity_after}/></div><nav className={styles.stages} aria-label="Demo investigation stages">{stages.map((s,i)=><button type="button" key={s} aria-pressed={stage===s} className={stage===s?styles.active:''} onClick={()=>setStage(s)}><span>0{i+1}</span>{s}</button>)}</nav><div className={styles.panel}>{stage==='Detect'?<><h3>{names[fault]}</h3><p>The request changes its explicit musical interest, while the task and catalog stay fixed. The boundary trace shows which profile reached the decision.</p></>:stage==='Diagnose'?<><h3>Find the divergent boundary.</h3><p>{readable(result.diagnosis)}</p><p>The diagnosis reads observed profile hashes and cache behavior.</p></>:stage==='Repair'?<><h3>Apply one supported correction.</h3><p>{readable(result.repair)}</p><p>Clear the affected state and execute the repaired route using its recorded model input.</p></>:<><h3>Verify every recovery control.</h3></>}</div><section className={styles.checkGroup} aria-label="Recorded recovery controls"><div className={styles.sectionHeading}><h3>RECOVERY CONTROLS</h3><span>Every check remains visible</span></div><ul className={styles.checks}>{Object.entries(result.checks).map(([name,pass])=><li key={name}><span>{readable(name)}</span><strong data-pass={pass}>{pass?'PASS':'FAIL'}</strong></li>)}</ul></section><div className={styles.ranking}><Films label="BEFORE / INJECTED FAULT" artist={result.requested_artist} rows={result.before}/><Films label="AFTER / REPAIRED ROUTE" artist={result.requested_artist} rows={result.after}/><Films label="HEALTHY / RECOVERY TARGET" artist={result.requested_artist} rows={result.healthy}/></div><div className={styles.traces}><TraceView title="Before repair" trace={result.trace} identity={result.identity_before}/><TraceView title="After repair" trace={result.repaired_trace} identity={result.identity_after}/></div></div>}</section>
    </>}

    <details className={styles.trace+' '+styles.captureDetails}><summary>Capture details &amp; evidence boundaries</summary><p>{summary?.notice??'Loading the verified record…'}</p>{summary?.status==='COMPLETE'&&pair&&<><div className={styles.totals}><div><strong>{summary.passing}/{summary.denominator}</strong><span>Controlled incident cases pass</span></div><div><strong>{summary.source_model_calls}</strong><span>Actual source model executions</span></div><div><strong>{summary.source_qloo_requests}</strong><span>Source Qloo queries including reused searches</span></div><div><strong>{summary.observed_repeat_recoveries}</strong><span>Observed recoveries across repeated incidents</span></div></div><p>{summary.pairs.length} artist pairs × 3 injected faults = {summary.denominator} cases, with three controlled repeats per case. Qloo maps explicit musical interests to movie context; the local agent makes the movie decision. AffinityQA checks whether that context and decision remain bound to the requested profile.</p><dl><div><dt>Captured run</dt><dd>{summary.run_id}</dd></div><div><dt>Frozen policy</dt><dd><code>{summary.policy_sha256}</code></dd></div><div><dt>Independent receipt fingerprint</dt><dd><code>{summary.receipt_sha256}</code></dd></div><div><dt>Repeat boundary</dt><dd>Three controlled repeats per incident; no population reliability estimate.</dd></div></dl></>}<div className={styles.evidenceBoundaries}><p>Passing profile-integrity controls does not establish cultural recommendation quality or authorize a production release. These gates describe the tested agent; demo hosting and publication have separate approvals.</p><p>The same twenty-film task goes through a faulty session, its diagnosis and repair. The pipeline runs now using verified decisions from the original real-model experiment.</p><p>Qloo supplies cultural tool context. This review checks profile integrity and causal recovery. Independent cultural quality remains unvalidated.</p></div></details><aside className={styles.history}><span className={styles.label}>EARLIER QUALITY EXPERIMENTS / PRESERVED FAILURES</span><p>Frozen historical development: 13/14 · FAIL. Independent movie-quality trial: 4/6 · FAIL. These prior results remain visible even without a replay bundle. New causal recovery does not establish individual taste satisfaction or revise historical scores.</p></aside></section></div>
  </WorkspaceShell>;
}
