import {useEffect,useState} from 'react';
import type {Snapshot,ReviewCase} from '../lib/review';
import {isMixed,score,signed,serial} from '../lib/review';
import {Arrow,FilmList,Pill} from './primitives';

export function Screening({data,item,stage,setStage,onSelect,openEvidence}:{data:Snapshot;item:ReviewCase;stage:number;setStage:(n:number)=>void;onSelect:(id:string)=>void;openEvidence:()=>void}){
  const [profile,setProfile]=useState<'A'|'B'>('B'),[repeat,setRepeat]=useState(0),[reference,setReference]=useState(false);
  useEffect(()=>{setReference(false)},[item.id]);
  const view=item.views[repeat],p=view.profiles[profile],first=view.order[0] as 'A'|'B',cacheHit=first!==profile;
  const mixed=isMixed(item),delta=p.after_agreement-p.before_agreement;
  const titles=['A change in taste. The same answer.','The signal was lost at the cache.','Separate profiles. Recompute decisions.','A repair needs a second opinion.'];
  return <section className="section-page screening-page"><div className="screen-heading"><div><span className="eyebrow">02 / SCREENING ROOM</span><h1>The <em>screen test.</em></h1></div><Pill tone="plum">Recorded walkthrough</Pill></div><div className="screen-context"><label><span>Choose a case</span><select aria-label="Choose a case" value={item.id} onChange={e=>onSelect(e.target.value)}>{data.cases.map((c,i)=><option key={c.id} value={c.id}>{serial(i)} · {c.artists.A} → {c.artists.B}</option>)}</select></label><div className="screen-context-note"><span>20 movies</span><i/>Fixed task<i/><span>One artist changes</span></div><button className="text-link" onClick={openEvidence}>View evidence <Arrow diagonal/></button></div><nav className="step-nav" aria-label="Evaluation stages">{['Detect','Diagnose','Repair','Verify'].map((name,i)=><button key={name} onClick={()=>setStage(i)} aria-current={stage===i?'step':undefined}><span>{serial(i)}</span><strong>{name}</strong><small>{['Spot the mismatch','Trace the cause','Inspect the change','Review the outcome'][i]}</small></button>)}</nav>
    <div className="stage-content" key={stage}><div className="stage-heading"><span className="eyebrow">ACT {serial(stage)} / {['THE MISMATCH','THE CAUSE','THE INTERVENTION','THE VERDICT'][stage]}</span><h2>{titles[stage]}</h2><p>{['The agent was given a new artist interest. Its shared cache served the first profile’s movie ranking again.','The declared test defect omitted the artist profile from the cache key. Changing taste did not trigger a fresh decision.','The recorded repair includes the profile in the cache key and clears old entries. The same model then ranks the same catalog again.','Qloo supplies an independent cultural reference for the fixed catalog. Compare the repaired decision with that reference before accepting the release.'][stage]}</p></div>
    {stage===0&&<><div className="signal-scene"><div><span className="eyebrow">PROFILE A</span><h3>{item.artists.A}</h3><span className="signal-tag">Artist interest</span></div><div className="scene-middle"><span className="orbit-link" aria-hidden="true">↔</span><span>Only the taste changes</span></div><div><span className="eyebrow">PROFILE B</span><h3>{item.artists.B}</h3><span className="signal-tag">Artist interest</span></div></div><div className="detect-result"><div className="detect-symbol">=</div><div><span className="eyebrow">OBSERVED / REPEAT 1</span><h3>Two profiles. One cached top five.</h3><p>Both received the first profile’s ranking. This is an intentionally injected defect, reproduced with real local model decisions.</p></div><Pill tone="coral">Profile collision</Pill></div><div className="shared-films"><span className="eyebrow">THE REUSED SHORTLIST</span><div>{item.views[0].profiles.B.before.map((m,i)=><div key={m.id}><span>{serial(i)}</span><strong>{m.title}</strong><small>{m.year}</small></div>)}</div></div></>}
    {stage===1&&<><div className="flow-scene"><div className="flow-node"><span className="eyebrow">INPUT</span><h3>A different artist</h3><p>{item.artists.A}<br/>{item.artists.B}</p><Pill tone="plum">Different signals</Pill></div><Arrow/><div className="flow-node fault-node"><span className="eyebrow">SHARED CACHE</span><h3>The profile is missing</h3><code>key = task</code><p>Both requests reach the same entry.</p><Pill tone="coral">Collision point</Pill></div><Arrow/><div className="flow-node"><span className="eyebrow">OUTPUT</span><h3>An unchanged ranking</h3><p>The second profile receives the first profile’s decision.</p><Pill>Wrong profile reused</Pill></div></div><aside className="method-note"><span>WHY QLOO MATTERS</span><p>The Qloo references change across the two profiles, while the faulty agent does not. The cache trace identifies this injected defect; reference agreement separately tests the quality of the proposed fix.</p></aside></>}
    {stage===2&&<><div className="repair-scene"><article><span className="eyebrow">BEFORE</span><h3>One entry for every taste.</h3><div className="cache-block"><span>Task</span><Arrow/><strong>Shared response</strong></div><p>Artist interests do not participate in the key.</p><code>cache_scope: task</code></article><article><span className="eyebrow">AFTER / RECORDED REPAIR</span><h3>A place for each profile.</h3><div className="cache-block"><span>Task + profile A</span><Arrow/><strong>Response A</strong></div><div className="cache-block"><span>Task + profile B</span><Arrow/><strong>Response B</strong></div><code>cache_scope: profile</code></article></div><div className="repair-receipt"><span className="receipt-check">✓</span><div><strong>Applied and retested in the recorded run.</strong><p>{data.cases.filter(c=>c.structural_gate==='PASS').length} of {data.case_count} reserved cases passed cache isolation checks. Recommendation quality is assessed in the next step.</p></div><span className="eyebrow">SAME MODEL · SAME CATALOG</span></div></>}
    {stage===3&&<><div className="verdict-banner"><div><Pill tone={mixed?'coral':'plum'}>{mixed?'Mixed quality outcome':'Observed agreement gain'}</Pill><h3>{mixed?'Keep this release under review.':'The repair improved this case.'}</h3><p>{mixed?'Some paired comparisons improved; others regressed. A better average is not enough.':'Every recorded paired comparison improved. Broader validation and a release threshold are still required.'}</p></div><div className="verdict-range"><span>PAIRED AGREEMENT CHANGE</span><strong>{signed(item.delta.min)} <i>to</i> {signed(item.delta.max)}</strong><small>Release not validated</small></div></div><div className="comparison-controls"><div className="profile-switch" role="group" aria-label="Inspect profile">{(['A','B'] as const).map(label=><button key={label} aria-pressed={profile===label} onClick={()=>setProfile(label)}>{label}<span>{item.artists[label]}</span></button>)}</div><label><span>Recorded repeat</span><select aria-label="Recorded repeat" value={repeat} onChange={e=>setRepeat(Number(e.target.value))}>{item.views.map((v,i)=><option value={i} key={i}>{v.repeat} · {v.order==='AB'?'A then B':'B then A'}</option>)}</select></label><button className="text-link" onClick={()=>setReference(!reference)} aria-expanded={reference}>{reference?'Hide':'Show'} Qloo ranking <span>{reference?'−':'+'}</span></button></div><div className={'ranking-comparison'+(reference?' with-reference':'')}><article><div className="rank-label"><span>AGENT / BEFORE</span><Pill tone={cacheHit?'coral':'neutral'}>{cacheHit?'Wrong profile':'First entry'}</Pill></div><h3>{p.artist}</h3><p>{cacheHit?'Reused the response for '+item.artists[first]+'.':'This profile filled the cache first.'}</p><FilmList movies={p.before}/><div className="agreement"><span>Qloo agreement</span><strong>{score(p.before_agreement)}</strong></div></article>{reference&&<article className="reference-column"><div className="rank-label"><span>QLOO / REFERENCE</span><Pill tone="plum">3 stable repeats</Pill></div><h3>A cultural reference.</h3><p>Fixed catalog, conditioned on {p.artist}.</p><FilmList movies={p.reference}/><div className="agreement"><span>Observed noise</span><strong>{score(item.reference_noise)}</strong></div></article>}<article className="after-column"><div className="rank-label"><span>AGENT / AFTER</span><Pill tone={delta<0?'coral':'plum'}>{delta<0?'Agreement fell':'Profile isolated'}</Pill></div><h3>{p.artist}</h3><p>Recomputed with its own cache entry.</p><FilmList movies={p.after} compare={p.before}/><div className="agreement"><span>Qloo agreement</span><strong>{score(p.after_agreement)}<small className={delta<0?'negative':'positive'}>{signed(delta)}</small></strong></div></article></div><p className="metric-note">Agreement is an ordinal score from 0 to 1, not a satisfaction percentage. Scores use three Qloo repeats; the reference list shows the first. “New” means absent from the previous top five.</p></>}
    </div><div className="stage-footer"><span><span className="status-dot"/> Recorded decisions · no new model or Qloo calls</span><div>{stage>0&&<button className="button quiet" onClick={()=>setStage(stage-1)}>Back</button>}{stage<3?<button className="button primary" onClick={()=>setStage(stage+1)}>Continue to {['','diagnosis','repair','verification'][stage+1]} <Arrow/></button>:<button className="button primary" onClick={openEvidence}>Open the evidence archive <Arrow/></button>}</div></div></section>;
}
